packages:
  - packages/*
  - "!packages/axios"
  - "!packages/redis"
  - "!packages/jsonwebtoken"
  - "!packages/form-data"
  - "!@karinjs/sqlite3-cjs"

neverBuiltDependencies:
  - "@karinjs/sqlite3"
  - "@karinjs/sqlite3-cjs"
  - "packages/sqlite3-cjs"
