import * as axios from 'axios'
import {
  Axios,
  AxiosError,
  CanceledError,
  isCancel,
  all,
  isAxiosError,
  spread,
  toFormData,
  AxiosHeaders,
  HttpStatusCode,
  formToJSON,
  getAdapter,
  mergeConfig,
} from 'axios'

export default axios.default
export {
  Axios,
  AxiosError,
  CanceledError,
  isCancel,
  all,
  isAxiosError,
  spread,
  toFormData,
  AxiosHeaders,
  HttpStatusCode,
  formToJSON,
  getAdapter,
  mergeConfig,
}

export type {
  CancelToken,
  Cancel,
  AxiosHeaderValue,
  RawAxiosRequestHeaders,
  AxiosRequestHeaders,
  RawAxiosResponseHeaders,
  AxiosResponseHeaders,
  AxiosResponseTransformer,
  AxiosAdapter,
  AxiosBasicCredentials,
  AxiosProxyConfig,
  Method,
  ResponseType,
  responseEncoding,
  TransitionalOptions,
  GenericAbortSignal,
  FormDataVisitorHelpers,
  SerializerVisitor,
  SerializerOptions,
  FormSerializerOptions,
  ParamEncoder,
  CustomParamsSerializer,
  ParamsSerializerOptions,
  AxiosProgressEvent,
  AddressFamily,
  LookupAddressEntry,
  LookupAddress,
  AxiosRequestConfig,
  RawAxiosRequestConfig,
  InternalAxiosRequestConfig,
  HeadersDefaults,
  AxiosDefaults,
  CreateAxiosDefaults,
  AxiosResponse,
  AxiosPromise,
  CancelStatic,
  Canceler,
  CancelTokenStatic,
  CancelTokenSource,
  AxiosInterceptorOptions,
  AxiosInterceptorManager,
  AxiosInstance,
  GenericFormData,
  GenericHTMLFormElement,
  AxiosStatic,
} from 'axios'
